name: Validate HACS

on:
  push:
    paths:
      - 'custom_components/**'
      - '.github/workflows/validate_hacs.yml'
  pull_request:
    paths:
      - 'custom_components/**'
      - '.github/workflows/validate_hacs.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands
